program: src/mlc_greek_bert/train.py
command:
  - ${env}
  - python
  - -m
  - mlc_greek_bert.train
  - --config
  - src/mlc_greek_bert/mlc_greek_bert.yaml
  - --sweep
method: bayes
metric:
  name: val_micro_f1
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5

parameters:
  learning_rate:
    distribution: log_uniform_values
    min: 1.0e-5
    max: 5.0e-5

  dropout:
    values: [0.1, 0.2, 0.3]

  batch_size:
    values: [8, 16]

  grad_accum_steps:
    values: [2, 4]

  warmup_ratio:
    values: [0.05, 0.1, 0.2]

  weight_decay:
    values: [0.0, 0.01, 0.05]

  loss:
    values: ["bce_pos_weight", "asl"]

  epochs:
    value: 10
